<a href="https://colab.research.google.com/github/jasonnonstop10/Datascilab/blob/main/CSC345_Week4a_proximity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# CSC345 -- Week#4a -- mini-lab  -- Getting to know your data
#                     Part1-- built-in various proximity-measures
# 
# Ref: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html
#      See above web for the formula definition of each proximity measure
#
# Instruction:
#          
# 1) Try to edit the given code with other proximity parameters such as 
#    'cityblock', 'cosine', 'euclidean', 'manhattan', 'hamming', 'jaccard', 
#    'mahalanobis', 'chebyshev', 'canbera', 'matching', ...
# 2) Guess/manually calculate the result before you run this code
# 3) Run your code and compare the result for each type of proximity measure
# 4) What are jaccard similarity of object(0,1) and jaccard of object(0,2)?
#--------------------------------------
#
from sklearn.metrics import pairwise_distances
import numpy as np


x = np.asarray([[1,2,3],[6,7,8],[0,3,4]]) 
print('\nManhattan =')
m = pairwise_distances(x, x, 'manhattan')
print(m)
print('\nEuclidean =')
e = pairwise_distances(x, x, 'euclidean')
print(e)
print('\nCosine =')
c = pairwise_distances(x, x, 'cosine')
print(c)



Manhattan =
[[ 0. 15.  3.]
 [15.  0. 14.]
 [ 3. 14.  0.]]

Euclidean =
[[0.         8.66025404 1.73205081]
 [8.66025404 0.         8.24621125]
 [1.73205081 8.24621125 0.        ]]

Cosine =
[[0.         0.03662466 0.03785953]
 [0.03662466 0.         0.13161416]
 [0.03785953 0.13161416 0.        ]]
